### ISSUE TITLE
Cannot uninstall SCIM Plugin on Keycloak 24.0.3

### ISSUE THREAD

**Issue by maqnius** [Captain-P-Goldfish/scim-for-keycloak#115]
Edit: Using the plugin `scim-for-keycloak-kc-24-2.1.0-free.jar`

When uninstalling the Plugin by removing the jar file from the Plugins folder, it breaks the Keycloak installation and I cannot run build again.

The error suggests, that it expects the jar file to be present. I looks related to [Keycloak Issue #24459](https://github.com/keycloak/keycloak/issues/24459) which *should* be fixed. Maybe it can serve as a hint, at least :) I cannot figure out, if this is a Plugin or Keycloak Issue.

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: java.lang.RuntimeException: Failed to open /home/keycloak2023/keycloak-24.0.3/lib/../providers/scim-for-keycloak-kc-24-2.1.0-free.jar
	at io.quarkus.bootstrap.runner.JarResource.ensureJarFileIsOpen(JarResource.java:172)
	at io.quarkus.bootstrap.runner.JarResource.readLockAcquireAndGetJarReference(JarResource.java:153)
	at io.quarkus.bootstrap.runner.JarResource.getResourceData(JarResource.java:72)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:99)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
	at org.keycloak.quarkus.runtime.Environment.isWindows(Environment.java:157)
	at org.keycloak.quarkus.runtime.Environment.getCommand(Environment.java:96)
	at org.keycloak.quarkus.runtime.cli.Picocli.createCommandLine(Picocli.java:502)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:103)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
	... 6 more
Caused by: java.nio.file.NoSuchFileException: /home/keycloak2023/keycloak-24.0.3/lib/../providers/scim-for-keycloak-kc-24-2.1.0-free.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1428)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
	at io.smallrye.common.io.jar.JarFiles.create(JarFiles.java:33)
	at io.quarkus.bootstrap.runner.JarResource.ensureJarFileIsOpen(JarResource.java:170)
	... 15 more

```

**Comment by Captain-P-Goldfish** [comment]
I have finally understood where the problem is.
I will try to fix this in a later release

**Comment by maqnius** [comment]
Thank you very much, if there's anything I can do, let me know :)

**Comment by Captain-P-Goldfish** [comment]
successfully resolved. Will be available with the next release. But the next release will take some time. I still got another feature-request for it.

**Comment by maqnius** [comment]
Great News! Thank you very much!
