### ISSUE TITLE
kc-26-2.3.3-free doesn't work with keycloak-26.0.x

### ISSUE THREAD

**Issue by igel1** [Captain-P-Goldfish/scim-for-keycloak#130]
Tried to install your latest scim software for the first time and ... it failed.
(tried the previous version 25 as well - seems to work properly with keycloak 25).

Here is the setup that failed for me:

Keycloak:        keycloak-26.0.5
Scim:               kc-26-2.3.3-free
Openjdk:         21
OS:                  ubuntu   (latest official ubuntu docker image)
Env:                 running within an docker container on my laptop (Mac)

Error message when starting keycloak with "kc.sh start-dev"):

```root@a2e441a2ca48:/opt/keycloak/keycloak-26.0.5/bin# ./kc.sh start-dev
2024-11-21 20:25:38,422 WARN  [de.captaingoldfish.scim.sdk.keycloak.LicenseKeyValidatorImpl] (main) License key will expire in less than 12 days at 'Tue, 3 Dec 2024 01:00:00 +0100'
2024-11-21 20:25:38,423 INFO  [de.captaingoldfish.scim.sdk.keycloak.LicenseKeyValidatorImpl] (main) License key was successfully validated. Initializing SCIM for keycloak
2024-11-21 20:25:38,423 INFO  [de.captaingoldfish.scim.sdk.keycloak.provider.ScimEndpointProviderFactory] (main) Reading SCIM configuration properties. Accepted properties are:

environment: KC_SPI_THEME_WELCOME_THEME = scim
property   :    spi-theme-welcome-theme = scim
default    :
[this property MUST be present with the value "scim"!]

environment: KC_SPI_REALM_RESTAPI_EXTENSION_SCIM_REPAIR_DATABASE = false
property   :    spi-realm-restapi-extension-scim-repair-database = false
[try to fix broken database entries. This can be used in case that the SCIM configuration is broken.]

environment: KC_SPI_REALM_RESTAPI_EXTENSION_SCIM_ACCEPT_ADMIN_CLI_LOGIN = false
property   :    spi-realm-restapi-extension-scim-accept-admin-cli-login = false
[accept admin-cli AccessTokens for login on SCIM backend administration console]

environment: KC_SPI_REALM_RESTAPI_EXTENSION_SCIM_IMPORT_SCIM_CONFIG = false
property   :    spi-realm-restapi-extension-scim-import-scim-config = false
default    :
[import SCIM configuration from "${kc.home}/data/import/scim"]

environment: KC_SPI_REALM_RESTAPI_EXTENSION_SCIM_LICENSE_KEY
property   :    spi-realm-restapi-extension-scim-license-key
default    :
[required for the free version to activate the SCIM functionality]

environment: KC_SPI_REALM_RESTAPI_EXTENSION_SCIM_ADMIN_URL_CHECK = strict
property   :    spi-realm-restapi-extension-scim-admin-url-check = strict
values     : [strict, no-context-path]
default    : strict
description: strict          -> request URL and configured Keycloak URL must match exactly.
             no-context-path -> only http-scheme (http or https), hostname and port need to match the request URL.

having some troubles? You can find some common problems and the solution here: https://scim-for-keycloak.de/faq

2024-11-21 20:25:39,566 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Starting Infinispan embedded cache manager
2024-11-21 20:25:39,659 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for sessions to 10000 entries.
2024-11-21 20:25:39,659 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for clientSessions to 10000 entries.
2024-11-21 20:25:39,659 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineSessions to 10000 entries.
2024-11-21 20:25:39,659 INFO  [org.keycloak.quarkus.runtime.storage.infinispan.CacheManagerFactory] (main) Persistent user sessions enabled and no memory limit found in configuration. Setting max entries for offlineClientSessions to 10000 entries.
2024-11-21 20:25:39,848 INFO  [org.infinispan.CONTAINER] (ForkJoinPool.commonPool-worker-1) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2024-11-21 20:25:40,298 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_810479, Site name: null
2024-11-21 20:25:40,300 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-11-21 20:25:40,301 INFO  [de.captaingoldfish.scim.sdk.keycloak.scim_client.provider.ScimClientDatastoreProviderFactory] (main) Initialized de.captaingoldfish.scim.sdk.keycloak.scim_client.provider.ScimClientDatastoreProviderFactory
2024-11-21 20:25:40,763 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
2024-11-21 20:25:41,102 ERROR [liquibase.changelog.ChangeSet] (main) ChangeSet META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com encountered an exception.: liquibase.exception.DatabaseException: Table "APPLICATION_DEFAULT_ROLES" already exists; SQL statement:
CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL) [42101-230] [Failed SQL: (42101) CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:476)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:83)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:185)
	at liquibase.executor.AbstractExecutor.execute(AbstractExecutor.java:141)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1189)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:775)
	at liquibase.changelog.visitor.UpdateVisitor.executeAcceptedChange(UpdateVisitor.java:119)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:68)
	at liquibase.changelog.ChangeLogIterator.lambda$run$0(ChangeLogIterator.java:131)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.changelog.ChangeLogIterator.lambda$run$1(ChangeLogIterator.java:120)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:257)
	at liquibase.Scope.child(Scope.java:261)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:89)
	at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:113)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:111)
	at liquibase.command.core.UpdateCommandStep.run(UpdateCommandStep.java:105)
	at liquibase.command.CommandScope.execute(CommandScope.java:220)
	at liquibase.Liquibase.lambda$update$0(Liquibase.java:216)
	at liquibase.Scope.lambda$child$0(Scope.java:191)
	at liquibase.Scope.child(Scope.java:200)
	at liquibase.Scope.child(Scope.java:190)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Liquibase.runInScope(Liquibase.java:1290)
	at liquibase.Liquibase.update(Liquibase.java:205)
	at liquibase.Liquibase.update(Liquibase.java:188)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider.updateChangeSet(QuarkusJpaUpdaterProvider.java:191)
	at org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:106)
	at org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider.update(QuarkusJpaUpdaterProvider.java:84)
	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.update(QuarkusJpaConnectionProviderFactory.java:281)
	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.createOrUpdateSchema(QuarkusJpaConnectionProviderFactory.java:247)
	at org.keycloak.quarkus.runtime.storage.database.jpa.QuarkusJpaConnectionProviderFactory.postInit(QuarkusJpaConnectionProviderFactory.java:124)
	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.init(QuarkusKeycloakSessionFactory.java:105)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.createSessionFactory(QuarkusKeycloakApplication.java:67)
	at org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:90)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication.onStartupEvent(QuarkusKeycloakApplication.java:52)
	at org.keycloak.quarkus.runtime.integration.jaxrs.QuarkusKeycloakApplication_Observer_onStartupEvent_GNZ8m5QenZ9h9VNelo7awjUZFDE.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:156)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:107)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:119)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:146)
	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:57)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at org.keycloak.quarkus.runtime.cli.Picocli.run(Picocli.java:147)
	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:135)
	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:106)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "APPLICATION_DEFAULT_ROLES" already exists; SQL statement:
CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL) [42101-230]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.ddl.CreateTable.update(CreateTable.java:91)
	at org.h2.command.CommandContainer.update(CommandContainer.java:139)
	at org.h2.command.Command.executeUpdate(Command.java:304)
	at org.h2.command.Command.executeUpdate(Command.java:248)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:262)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:231)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:220)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:470)
	... 76 more


UPDATE SUMMARY
Run:                          0
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:          144

2024-11-21 20:25:41,110 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 1 ResultSet(s) and 0 Statement(s)
2024-11-21 20:25:41,110 WARN  [io.agroal.pool] (main) Datasource '<default>': JDBC resources leaked: 3 ResultSet(s) and 0 Statement(s)
2024-11-21 20:25:41,114 INFO  [com.arjuna.ats.jbossatx] (main) ARJUNA032014: Stopping transaction recovery manager
2024-11-21 20:25:41,332 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (development) mode
2024-11-21 20:25:41,333 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
2024-11-21 20:25:41,333 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table "APPLICATION_DEFAULT_ROLES" already exists; SQL statement:
CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL) [42101-230] [Failed SQL: (42101) CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
2024-11-21 20:25:41,333 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table "APPLICATION_DEFAULT_ROLES" already exists; SQL statement:
CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL) [42101-230] [Failed SQL: (42101) CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
2024-11-21 20:25:41,333 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for changeset META-INF/jpa-changelog-1.0.0.Final.xml::1.0.0.Final-KEYCLOAK-5461::sthorger@redhat.com:
     Reason: liquibase.exception.DatabaseException: Table "APPLICATION_DEFAULT_ROLES" already exists; SQL statement:
CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL) [42101-230] [Failed SQL: (42101) CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
2024-11-21 20:25:41,333 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Table "APPLICATION_DEFAULT_ROLES" already exists; SQL statement:
CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL) [42101-230] [Failed SQL: (42101) CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL)]
2024-11-21 20:25:41,333 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Table "APPLICATION_DEFAULT_ROLES" already exists; SQL statement:
CREATE TABLE PUBLIC.APPLICATION_DEFAULT_ROLES (APPLICATION_ID VARCHAR(36) NOT NULL, ROLE_ID VARCHAR(36) NOT NULL) [42101-230]
2024-11-21 20:25:41,333 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.```

**Comment by igel1** [comment]
Meanwhile I tried all other versions of keycloak-26.0.x - none of them works with kc-26-2.3.3-free.
That's why I changed the title to: "kc-26-2.3.3-free doesn't work with keycloak-26.0.x"

**Comment by Captain-P-Goldfish** [comment]
The problem occurs during database creation and it does **not** happen in the plugin database-creation but in the Keycloaks native liquibase database creation. So the problem you have is not plugin related. It should also occur with the plugin uninstalled.

It is that specific execution that fails that comes from Keycloak itself:
```xml
<databaseChangeLog logicalFilePath="META-INF/db2-jpa-changelog-1.0.0.Final.xml" xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.2.xsd">
    <changeSet author="sthorger@redhat.com" id="1.0.0.Final-KEYCLOAK-5461">
        <validCheckSum>7:cb16724583e9675711801c6875114f28</validCheckSum>
        <preConditions onSqlOutput="TEST" onFail="MARK_RAN">
            <dbms type="db2" />

            <not>
                <changeSetExecuted id="1.0.0.Final" author="sthorger@redhat.com" changeLogFile="META-INF/db2-jpa-changelog-1.0.0.Final.xml"/>
            </not>
        </preConditions>

        <createTable tableName="APPLICATION_DEFAULT_ROLES">
            <column name="APPLICATION_ID" type="VARCHAR(36)">
                <constraints nullable="false"/>
            </column>
            <column name="ROLE_ID" type="VARCHAR(36)">
                <constraints nullable="false"/>
            </column>
        </createTable>
...
```

Something probably broke down during migration. But the core problem seems to be that the databasechangelog entries in your table are missing.
But this is actually out of scope for this plugin.
